USE ICTPRG431_Query_5_Sub_Queries_and_Vertical_Join_Tasks;
GO

-- 1
SELECT M.*
FROM MOVIE9468 M
WHERE RELYEAR = 2003
ORDER BY RATINGCODE ASC, TMDB_SCORE ASC

-- 2
SELECT M.TITLE 'Movie Name', A.GENDER 'Gender', COUNT(A.ACTORNO) 'Num Roles'
FROM MOVIE9468 M
INNER JOIN CASTING9468 C
ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR9468 A
ON C.ACTORNO = A.ACTORNO
WHERE M.RELYEAR = 2001
GROUP BY A.GENDER, M.TITLE
ORDER BY M.TITLE DESC, A.GENDER DESC

-- 3
SELECT M.TITLE 'Movie Name', A.GENDER 'Gender', COUNT(A.ACTORNO) 'Num Roles'
FROM MOVIE9468 M
INNER JOIN CASTING9468 C
ON M.MOVIENO = C.MOVIENO
INNER JOIN ACTOR9468 A
ON C.ACTORNO = A.ACTORNO
WHERE M.RELYEAR = 2001
GROUP BY A.GENDER, M.TITLE
HAVING COUNT(A.ACTORNO) <= 2
ORDER BY M.TITLE DESC, A.GENDER DESC

-- 4
SELECT M.TITLE, A.FULLNAME, CT.COLOURCODE, CT.COLOURNAME, R.SHORTDESC
FROM MOVIE9468 M
INNER JOIN CASTING9468 CA
ON M.MOVIENO = CA.MOVIENO
INNER JOIN ACTOR9468 A
ON CA.ACTORNO = A.ACTORNO
INNER JOIN RATING9468 R
ON M.RATINGCODE = R.RATINGCODE
INNER JOIN COLOURTYPE9468 CT
ON M.COLOURCODE = CT.COLOURCODE

-- 5
SELECT A.FULLNAME, COUNT(C.ACTORNO) 'Num Castings'
FROM ACTOR9468 A
LEFT JOIN CASTING9468 C
ON C.ACTORNO = A.ACTORNO
GROUP BY A.FULLNAME, A.ACTORNO
HAVING COUNT(C.ACTORNO) >= 0

-- 6
SELECT A.FULLNAME, COUNT(C.ACTORNO) 'Num Castings'
FROM CASTING9468 C
RIGHT JOIN ACTOR9468 A
ON A.ACTORNO = C.ACTORNO
GROUP BY A.FULLNAME, A.ACTORNO
HAVING COUNT(C.ACTORNO) >= 0
ORDER BY COUNT(C.ACTORNO)

-- 7
SELECT M.*, A.*
FROM MOVIE9468 M
FULL OUTER JOIN CASTING9468 C
ON C.MOVIENO = M.MOVIENO
FULL OUTER JOIN ACTOR9468 A
ON A.ACTORNO = C.ACTORNO
ORDER BY M.MOVIENO

-- 8
SELECT C.ACTORNO
FROM ACTOR9468 A
INNER JOIN CASTING9468 C
ON C.ACTORNO = A.ACTORNO
WHERE A.GENDER = 'M'
GROUP BY C.ACTORNO
HAVING COUNT(C.ACTORNO) = 12

SELECT M.*
FROM MOVIE9468 M
INNER JOIN CASTING9468 C
ON C.MOVIENO = M.MOVIENO
WHERE C.ACTORNO IN (SELECT C.ACTORNO
                    FROM ACTOR9468 A
                    INNER JOIN CASTING9468 C
                    ON C.ACTORNO = A.ACTORNO
                    WHERE A.GENDER = 'M'
                    GROUP BY C.ACTORNO                   
                    HAVING COUNT(C.ACTORNO) = 12)

-- 9
SELECT M.TITLE, M.TMDB_SCORE * TMDB_VOTES 'Multiply'
FROM MOVIE9468 M
WHERE M.RATINGCODE = 'PG' AND M.RUNTIME < 120

-- 10
SELECT A.BIRTHDATE, 
DATENAME(WEEKDAY, A.BIRTHDATE) 'DayOfWeek', 
DATENAME(DAY, A.BIRTHDATE) 'DayOfMonth',
DATENAME(MONTH, A.BIRTHDATE) 'MonthName',
DATEPART(MONTH, A.BIRTHDATE) 'MonthNum',
DATENAME(YEAR, A.BIRTHDATE) 'Year'
FROM ACTOR9468 A
